"""Backwards-compatible RAG settings wrapper around shared config."""

from aqgpt_core.config import (
    MAX_CHUNKS_PER_URL,
    MAX_CONTEXT_CHUNKS,
    RAG_CHROMA_DIR,
    RAG_COLLECTION_NAME,
    RAG_EMBED_MODEL,
    RAG_GENERATION_CONFIG,
    RAG_OLLAMA_BASE_URL,
    RAG_TOP_K,
    RAG_VLLM_BASE_URL,
)

RAG_GENERATION_PROVIDER = RAG_GENERATION_CONFIG.provider
RAG_GENERATION_MODEL = RAG_GENERATION_CONFIG.model
